services:
  oraclefritzbot:
    build: .
    image: oraclefritzbot:latest
    container_name: oracle-fritz-bot
    environment:
      - GCN_CLIENT_ID=<your client id>
      - GCN_CLIENT_SECRET=<your client secret>
      - GCN_GROUP_ID=oraclefritzbot
      - GCN_ALWAYS_EARLIEST=True # change to False in production
      - SKYPORTAL_HOST="https://fritz.science"
      - SKYPORTAL_TOKEN=<your token>
